OBJS = 	../common/sbrk.o \
	    ../common/clock.o \
	    ../common/uart.o \
	    ../common/led.o \
	    slave_i2c.o ring.o events.o echo_handler.o emdisplay_handler.o

BINARY = slave_i2c_example

DEVICE = STM32F446RE

include ../../Makefile.include

