OBJS = 	../common/sbrk.o \
	    ../common/clock.o \
	    ../common/uart.o \
	    ../common/led.o \
	    ring.o events.o echo_handler.o

BINARY = slave_i2c

DEVICE = STM32F446RE

include ../../Makefile.include

